
PROJECT_NAME=mq-rdqm
PROJECT_REV=5
PRJ_ID=$(PROJECT_NAME)_$(PROJECT_REV)

INSTANCE_FILE=$(PRJ_ID).ini
INSTALL_DIR=/home/centos/work
# AWS NAME TAGS FOR COMPONENTS
# AWS NAME TAGS FOR COMPONENTS
# AWS NAME TAGS FOR COMPONENTS
# BASE NAMES
A_NAME=banana
B_NAME=grape
KEY_NAME=$(PRJ_ID)_KEY
VPC_A_NAME=$(A_NAME)
VPC_B_NAME=$(B_NAME)
SUBNET_A_A_NAME=$(A_NAME)_A
SUBNET_A_B_NAME=$(A_NAME)_B
SUBNET_A_C_NAME=$(A_NAME)_C
SUBNET_A_D_NAME=$(A_NAME)_BASTION

SUBNET_B_A_NAME=$(A_NAME)_A
SUBNET_B_B_NAME=$(A_NAME)_B
SUBNET_B_C_NAME=$(A_NAME)_C
SUBNET_B_D_NAME=$(B_NAME)_BASTION

GATEWAY_A_NAME=$(A_NAME)_GW
GATEWAY_B_NAME=$(B_NAME)_GW


ATTACHMENT_A_NAME=$(A_NAME)
ATTACHMENT_B_NAME=$(B_NAME)

PEERING_NAME=$(A_NAME)_$(B_NAME)_CONN

IGW_A_NAME=$(A_NAME)_IGW
IGW_B_NAME=$(B_NAME)_IGW
NAT_GW_A_PUBLIC_IP_NAME=$(A_NAME)_NAT_GW
NAT_GW_B_PUBLIC_IP_NAME=$(B_NAME)_NAT_GW
NAT_GW_A_NAME=$(A_NAME)_NAT_GW
NAT_GW_B_NAME=$(B_NAME)_NAT_GW


COMPUTE_NAME_A_A=mq-a-a
COMPUTE_NAME_A_B=mq-a-b
COMPUTE_NAME_A_C=mq-a-c
COMPUTE_NAME_B_A=mq-b-a
COMPUTE_NAME_B_B=mq-b-b
COMPUTE_NAME_B_C=mq-b-c
BASTION_A_NAME=mq-bastion-a
BASTION_B_NAME=mq-bastion-b

SECURITY_GROUP_A_NAME=$(PRJ_ID)_$(A_NAME)_SG
SECURITY_GROUP_B_NAME=$(PRJ_ID)_$(B_NAME)_SG
BASTION_A_PUBLIC_IP_NAME=$(A_NAME)_bastion
BASTION_B_PUBLIC_IP_NAME=$(B_NAME)_bastion
ROUTE_TABLE_A_NAME=$(PRJ_ID)_RT_A
ROUTE_TABLE_B_NAME=$(PRJ_ID)_RT_B
# ******************************

# AWS REGIONS
REGION_A=us-east-1
REGION_B=us-west-2
ZONE_A_A:=$(REGION_A)a
ZONE_A_B:=$(REGION_A)b
ZONE_A_C:=$(REGION_A)c
ZONE_B_A:=$(REGION_B)a
ZONE_B_B:=$(REGION_B)b
ZONE_B_C:=$(REGION_B)c
ZONES_A:=$(REGION_A)a $(REGION_A)b $(REGION_A)c
ZONES_B:=$(REGION_B)a $(REGION_B)b $(REGION_B)c



# VPC A (O=OCTET)
A_O1=10
A_O2=194
# SUBNET 
A_O3_1=0
A_O3_2=64
A_O3_3=128
A_O3_4=1

VPC_A_CIDR=$(A_O1).$(A_O2).0.0/16
VPC_A_SUBNET_A=$(A_O1).$(A_O2).$(A_O3_1).0/24
VPC_A_SUBNET_B=$(A_O1).$(A_O2).$(A_O3_2).0/24
VPC_A_SUBNET_C=$(A_O1).$(A_O2).$(A_O3_3).0/24
VPC_A_SUBNET_D=$(A_O1).$(A_O2).$(A_O3_4).0/24

# VPC B
B_O1=10
B_O2=195
# SUBNET 
B_O3_1=0
B_O3_2=64
B_O3_3=128
B_O3_4=1
VPC_B_CIDR=$(B_O1).$(B_O2).0.0/16
VPC_B_SUBNET_A=$(B_O1).$(B_O2).$(B_O3_1).0/24
VPC_B_SUBNET_B=$(B_O1).$(B_O2).$(B_O3_2).0/24
VPC_B_SUBNET_C=$(B_O1).$(B_O2).$(B_O3_3).0/24
VPC_B_SUBNET_D=$(B_O1).$(B_O2).$(B_O3_4).0/24




# COMPUTE
# BASTION
COMPUTE_Z_AMI=ami-0ee70e88eed976a1b
COMPUTE_Z_TYPE=t3.nano	
COMPUTE_Z_DISK_TYPE=GP2

# REGION A
COMPUTE_A_AMI=ami-0ee70e88eed976a1b

COMPUTE_A_TYPE=t3.xlarge
COMPUTE_A_DISK_TYPE=GP2

# REGION B
COMPUTE_B_AMI=ami-056c679fab9e48d8a
COMPUTE_B_TYPE=t3.xlarge
COMPUTE_B_DISK_TYPE=GP2


BASTION_A_IP=$(A_O1).$(A_O2).$(A_O3_4).4
BASTION_B_IP=$(B_O1).$(B_O2).$(B_O3_4).4
COMPUTE_A_A_IP=$(A_O1).$(A_O2).$(A_O3_1).4
COMPUTE_A_B_IP=$(A_O1).$(A_O2).$(A_O3_2).4
COMPUTE_A_C_IP=$(A_O1).$(A_O2).$(A_O3_3).4
COMPUTE_B_A_IP=$(B_O1).$(B_O2).$(B_O3_1).4
COMPUTE_B_B_IP=$(B_O1).$(B_O2).$(B_O3_2).4
COMPUTE_B_C_IP=$(B_O1).$(B_O2).$(B_O3_3).4

# SSHINFO FOR BASTOIN
DATA_DIR=data/$(PRJ_ID)
PEM_FILE=$(DATA_DIR)/ssh/id.rsa
MQM_PEM_FILE=$(DATA_DIR)/ssh/mqm.id_rsa
BASTION_USER=centos



# SSH
BASTION_A_SSH=$(BASTION_USER)@$(BASTION_A_PUBLIC_IP)
BASTION_B_SSH=$(BASTION_USER)@$(BASTION_B_PUBLIC_IP)
COMPUTE_A_A_SSH=$(BASTION_USER)@$(COMPUTE_A_A_IP)
COMPUTE_A_B_SSH=$(BASTION_USER)@$(COMPUTE_A_B_IP)
COMPUTE_A_C_SSH=$(BASTION_USER)@$(COMPUTE_A_C_IP)

COMPUTE_B_A_SSH=$(BASTION_USER)@$(COMPUTE_B_A_IP)
COMPUTE_B_B_SSH=$(BASTION_USER)@$(COMPUTE_B_B_IP)
COMPUTE_B_C_SSH=$(BASTION_USER)@$(COMPUTE_B_C_IP)

